### ISSUE TITLE
Требования к описанию ЭЭГ

### ISSUE THREAD

**Issue by Tsarevich13** [AI-is-out-there/2024-SkillFactory-NeuralNetworks#4]

**Comment by marszzzs** [comment]
Написала Требования к данным ЭЭГ, Вопросы для уточнения на созвоне, Концепцию проекта и План разработки (будут в дальнейшем дорабатываться проджектом)

[GoogleDoc](https://docs.google.com/document/d/1bogHtbntXj71CnbccrbKxygIDPY9IUEWTxqe7rTR8SA/edit?usp=sharing)
