### ISSUE TITLE
Стандарты оформления документации

### ISSUE THREAD

**Issue by Tsarevich13** [AI-is-out-there/2024-SkillFactory-NeuralNetworks#5]
После завершения конкретных этапов проекта, нужно будет составлять их описания - что было сделано и зачем?

Потому нужно подготовить вордовский документ, в котором будут описаны требования к оформлению такой документации (шрифты, отступы, интервалы и т.д.)

Было решено взять за основу **_те же требования, что  у дипломных работ_**.

**Comment by glkapustin** [comment]
> Good luck!

**Comment by glkapustin** [comment]
[ИИ для ЭЭГ, требования.docx](https://github.com/user-attachments/files/18158197/default.docx)
